FROM ubuntu:18.04

RUN apt update && \
    apt upgrade -y && \
    apt install curl -y

RUN curl -L https://bootstrap.saltstack.com -o install_salt.sh && \
    chmod +x install_salt.sh

RUN sh ./install_salt.sh -M

RUN apt install salt-ssh -y

EXPOSE 4505 4506


